// console.log("HUSN")

// var a = 12
// if (a>10){
//   a = 23
//   console.log("Age = "+a)
// }

// function fun(a,b){
//   console.log("Kuch Bhi!!!")
//   return a+b
// }

// let ab=fun();
// console.log(ab)

// let ab2=fun(5,7);
// console.log(ab2)


// function selectLang(language){
//   if(language=='c'){
//     function cCompiler(){
//       return "C Compiler";
//     }
//     data=cCompiler();
//   }
//   if(language=='java'){
//     function javaCompiler(){
//       return "Java Compiler";
//     }
//     data=javaCompiler();
//   }
//   return data;
// }

// const res = selectLang("c");
// console.log(res)

// const dive = document.getElementsByClassName("parent");
// console.dir(dive)
// dive[0].innerHTML="<h2 style=color:red;>ABES Something College</h2>"
// const h1 = document.createElement("h1")
// console.dir(h1)
// h1.innerText="This is generated by DOM.";
// console.log(h1)
// h1.style.backgroundColor='yellow'
// h1.style.padding='12px'
// dive[0].appendChild(h1)
// const img = document.createElement("img")
// console.log(img)
// img.src="../images/1stimg.jpg"
// img.setAttribute("height","200")
// img.setAttribute("width","200")
// dive[0].appendChild(img)

// const disp = document.getElementById("disp");
// console.dir(disp);
// function getData(){
//   console.log("Getdata Called")
//   disp.innerHTML="<h2>You have called get data</h2>"
// }

// const btn=document.getElementById("btn")
// btn.addEventListener("click",getData);

const prom = new promise ((resolve,reject)=>{
  let a = 12;
  if(a>10){
    resolve("Resolved")
  }else{
    reject("Rejected")
  }
});

promise.then((msg)=>{
  console.log(msg)
}).catch((error)=>
console.log(error))